spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plainplan?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: sxp19970809
    driver-class-name: com.mysql.cj.jdbc.Driver
